import { CreateCourseDto } from '@/dto/CreateCourseDto';
import { Department } from '@/enums';

export const dummyCourseList: CreateCourseDto[] = [
  {
    code: 'MATH 1101',
    name: 'Mathematics I',
    credit: 3,
    department: Department.CSE,
    semester: 1,
    isAutoAssign: true,
  },
  {
    code: 'ENG 1204',
    name: 'English II',
    credit: 3,
    department: Department.CSE,
    semester: 1,
    isAutoAssign: true,
  },
  {
    code: 'PHY 1302',
    name: 'Physics II',
    credit: 3,
    department: Department.CSE,
    semester: 1,
    isAutoAssign: true,
  },
  {
    code: 'CSE 1102',
    name: 'Structured Programming Language',
    credit: 3,
    department: Department.CSE,
    semester: 1,
    isAutoAssign: true,
  },
  {
    code: 'CSE 1157',
    name: 'Structured Programming Language Lab Work',
    credit: 1,
    department: Department.CSE,
    semester: 1,
    isAutoAssign: true,
  },
  {
    code: 'CSE 1290',
    name: 'Software Development I (C Programming)',
    credit: 3,
    department: Department.CSE,
    semester: 2,
    isAutoAssign: true,
  },
  {
    code: 'CSE 1307',
    name: 'Object-Oriented Programming-I (C++)',
    credit: 3,
    department: Department.CSE,
    semester: 2,
    isAutoAssign: true,
  },
  {
    code: 'CSE 1360',
    name: 'Object-Oriented Programming-I Lab Work',
    credit: 1,
    department: Department.CSE,
    semester: 2,
    isAutoAssign: true,
  },
  {
    code: 'CSE 2111',
    name: 'Data Structure',
    credit: 3,
    department: Department.CSE,
    semester: 2,
    isAutoAssign: true,
  },
  {
    code: 'CSE 2162',
    name: 'Data Structure Lab Work',
    credit: 1,
    department: Department.CSE,
    semester: 2,
    isAutoAssign: true,
  },
  {
    code: 'MATH 1302',
    name: 'Mathematics II',
    credit: 2,
    department: Department.CSE,
    semester: 2,
    isAutoAssign: true,
  },
  {
    code: 'CSE 1205',
    name: 'Electrical Engineering and Circuit Analysis',
    credit: 3,
    department: Department.CSE,
    semester: 2,
    isAutoAssign: true,
  },
  {
    code: 'CSE 1259',
    name: 'Electrical Engineering and Circuit Analysis Lab Work',
    credit: 1,
    department: Department.CSE,
    semester: 2,
    isAutoAssign: true,
  },
  {
    code: 'CSE 2215',
    name: 'Digital Logic Design',
    credit: 3,
    department: Department.CSE,
    semester: 3,
    isAutoAssign: true,
  },
  {
    code: 'CSE 2263',
    name: 'Algorithms Design & Analysis',
    credit: 3,
    department: Department.CSE,
    semester: 3,
    isAutoAssign: true,
  },
  {
    code: 'CSE 2264',
    name: 'Algorithms Lab Work',
    credit: 1,
    department: Department.CSE,
    semester: 3,
    isAutoAssign: true,
  },
  {
    code: 'CSE 2265',
    name: 'Digital Logic Design Lab Work',
    credit: 1,
    department: Department.CSE,
    semester: 3,
    isAutoAssign: true,
  },
  {
    code: 'CSE 2319',
    name: 'Database Management System',
    credit: 3,
    department: Department.CSE,
    semester: 3,
    isAutoAssign: true,
  },
  {
    code: 'CSE 2367',
    name: 'Database Management Systems Lab Work',
    credit: 1,
    department: Department.CSE,
    semester: 3,
    isAutoAssign: true,
  },
  {
    code: 'MATH 2103',
    name: 'Mathematics III',
    credit: 3,
    department: Department.CSE,
    semester: 3,
    isAutoAssign: true,
  },
];
